In [136]:
import pandas as pd

In [137]:
df = pd.read_excel(r"E:\Panda\Excel_ sheet_for _working\super-store-sales-dataset-main\super-store-sales-dataset-main\Orders.xlsx")

In [138]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,7981,CA-2014-103800,2014-01-03,2014-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,740,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,741,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,742,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,1760,CA-2014-141817,2014-01-05,2014-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,7681,CA-2014-133592,2014-12-31,2015-01-07,Standard Class,KM-16375,Katherine Murray,Home Office,United States,Providence,...,2908,East,FUR-BO-10000362,Furniture,Bookcases,Sauder Inglewood Library Bookcases,341.960,2,0.0,78.6508
1989,7682,CA-2014-133592,2014-12-31,2015-01-07,Standard Class,KM-16375,Katherine Murray,Home Office,United States,Providence,...,2908,East,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",605.880,6,0.0,151.4700
1990,8603,US-2014-133949,2014-12-31,2014-12-31,Same Day,JL-15175,James Lanier,Home Office,United States,Reno,...,89502,West,TEC-PH-10004908,Technology,Phones,Panasonic KX TS3282W Corded phone,475.944,7,0.2,59.4930
1991,8804,CA-2014-157644,2014-12-31,2015-01-01,First Class,AH-10030,Aaron Hawkins,Corporate,United States,New York City,...,10035,East,TEC-AC-10003614,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,34.770,3,0.0,11.4741
1992,8805,CA-2014-157644,2014-12-31,2015-01-01,First Class,AH-10030,Aaron Hawkins,Corporate,United States,New York City,...,10035,East,OFF-LA-10003148,Office Supplies,Labels,Avery 51,18.900,3,0.0,8.6940

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1993 entries, 0 to 1992
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1993 non-null   int64
 1   Order ID       1993 non-null   object
 2   Order Date     1993 non-null   datetime64[ns]
 3   Ship Date      1993 non-null   datetime64[ns]
 4   Ship Mode      1993 non-null   object
 5   Customer ID    1993 non-null   object
 6   Customer Name  1993 non-null   object
 7   Segment        1993 non-null   object
 8   Country        1993 non-null   object
 9   City           1993 non-null   object
 10  State          1993 non-null   object
 11  Postal Code    1993 non-null   int64
 12  Region         1993 non-null   object
 13  Product ID     1993 non-null   object
 14  Category       1993 non-null   object
 15  Sub-Category   1993 non-null   object
 16  Product Name   1993 non-null   object
 17  Sales          1993 non-null   float64
 18  Quantity       1993 non-null   int64
 19  Discount       1993 non-null   float64
 20  Profit         1993 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 327.1+ KB

In [140]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,1993.000000,1993,1993,1993.000000,1993.000000,1993.000000,1993.000000,1993.000000
mean,4969.400401,2014-08-11 11:47:21.344706560,2014-08-15 11:43:01.234320128,56834.544405,242.974159,3.803813,0.158284,24.858994
min,6.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1841.000000,0.852000,1.000000,0.000000,-3701.892800
25%,2613.000000,2014-05-21 00:00:00,2014-05-26 00:00:00,27511.000000,16.224000,2.000000,0.000000,1.663200
50%,4899.000000,2014-09-07 00:00:00,2014-09-11 00:00:00,60623.000000,51.968000,3.000000,0.200000,8.217000
75%,7508.000000,2014-11-10 00:00:00,2014-11-14 00:00:00,90008.000000,218.750000,5.000000,0.200000,28.347900
max,9990.000000,2014-12-31 00:00:00,2015-01-07 00:00:00,99301.000000,22638.480000,14.000000,0.800000,4630.475500
std,2895.777922,NaN,NaN,31774.557583,754.053357,2.242154,0.205716,198.931675

In [141]:
df.groupby("Category")[["Sales","Profit"]].sum().sort_values(by="Sales",ascending=False)

                       Sales      Profit
Category
Technology       175278.2330  21492.8325
Furniture        157192.8531   5457.7255
Office Supplies  151776.4120  22593.4161

In [142]:
Sub_Category= df.groupby("Sub-Category")["Profit"].sum().sort_values(ascending=False)

In [143]:
Sub_Category

Sub-Category
Phones         11808.0053
Chairs          6955.0470
Accessories     6402.7150
Paper           6371.0214
Binders         4739.7160
Storage         4166.2788
Copiers         2912.9433
Appliances      2459.4999
Furnishings     1972.8919
Envelopes       1495.4788
Art             1406.8031
Labels          1286.0042
Supplies         490.0556
Machines         369.1689
Fasteners        178.5583
Bookcases       -346.1707
Tables         -3124.0427
Name: Profit, dtype: float64

In [144]:
Loss_Making_Sub_Category = Sub_Category[Sub_Category<0]

In [145]:
Loss_Making_Sub_Category.sort_values(ascending=True)

Sub-Category
Tables      -3124.0427
Bookcases    -346.1707
Name: Profit, dtype: float64

In [146]:
Sales= df.groupby("Sub-Category")["Sales"].sum()

In [147]:
Sales

Sub-Category
Accessories    25014.2720
Appliances     15313.6250
Art             6057.9820
Binders        43488.2650
Bookcases      20036.6776
Chairs         77241.5760
Copiers        10849.7820
Envelopes       3855.7500
Fasteners        661.3280
Furnishings    13826.2340
Labels          2841.3940
Machines       62023.3730
Paper          14834.9560
Phones         77390.8060
Storage        50329.0420
Supplies       14394.0700
Tables         46088.3655
Name: Sales, dtype: float64

In [148]:
Average_Sales = Sales.mean()

In [149]:
Average_Sales

28485.146947058824

In [150]:
Sales_Greater_Average_Sales=Sales[Sales>Average_Sales]

In [151]:
Sales_Greater_Average_Sales.sort_values(ascending=False)

Sub-Category
Phones      77390.8060
Chairs      77241.5760
Machines    62023.3730
Storage     50329.0420
Tables      46088.3655
Binders     43488.2650
Name: Sales, dtype: float64

In [152]:
Total_profit =df["Profit"].sum()

In [153]:
Total_profit

49543.974099999985

In [154]:
Category = df.groupby("Category")["Profit"].sum()

In [155]:
Total_Profit_Average=Category.mean()

In [156]:
Total_Profit_Average=Category.mean()

In [157]:
Total_Profit_Average

16514.65803333333

In [158]:
Category_Profit_greater_Total_Profit_Average=Category[Category>Total_Profit_Average]

In [159]:
Category_Profit_greater_Total_Profit_Average

Category
Office Supplies    22593.4161
Technology         21492.8325
Name: Profit, dtype: float64

In [160]:
Top_3_Customers=df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(3)

In [161]:
Top_3_Customers

Customer Name
Sean Miller     23661.228
Sanjit Chand    12876.480
Becky Martin    10539.896
Name: Sales, dtype: float64

In [162]:
Region_Max_Total_Profit=df.groupby("Region")["Profit"].sum().sort_values(ascending=False).head(1)

In [163]:
Region_Max_Total_Profit

Region
West    20065.6912
Name: Profit, dtype: float64

In [164]:
Five_Products_Total_Quantity = df.groupby("Product Name")["Quantity"].sum().sort_values(ascending=False).head()

In [165]:
Five_Products_Total_Quantity

Product Name
Staple envelope                           54
Staples                                   52
KI Adjustable-Height Table                29
Southworth 100% Résumé Paper, 24lb.       28
Maxell 74 Minute CD-R Spindle, 50/Pack    24
Name: Quantity, dtype: int64

In [166]:
Total_Sales=df.groupby("Category")["Sales"].sum()

In [167]:
Total_Sales

Category
Furniture          157192.8531
Office Supplies    151776.4120
Technology         175278.2330
Name: Sales, dtype: float64

In [168]:
Average_Category_Sales=Total_Sales.mean()

In [169]:
Average_Category_Sales

161415.8327

In [171]:
Total_Sales_greater_Average_Category_Sales= Total_Sales[Total_Sales>Average_Category_Sales]

In [172]:
Total_Sales_greater_Average_Category_Sales

Category
Technology    175278.233
Name: Sales, dtype: float64